### ISSUE TITLE
【功能请求】RSS加上原图链接方便一键下载

### ISSUE THREAD

**Issue by wenketel** [chitosai/PixivRss#2]
[![2017-9-1_21-28-41.jpg](https://i.loli.net/2017/09/01/59a962af0a8fc.jpg)](https://i.loli.net/2017/09/01/59a962af0a8fc.jpg)
https://www.flickr.com/services/feeds/photos_public.gne?id=25496978@N06&lang=zh-hant-hk&format=atom
Flickr的RSS在inoreader可以有一个原始附件的链接，pixivRSS也有这样一个链接直接下载原图就好了。

**Comment by chitosai** [comment]
我的策略就是鼓励大家点开p站，给画师点个赞，所以我不会直接输出原图的。

**Comment by wenketel** [comment]
可以给人两种选择嘛，想下载的人可以下载，想去p站的人去p站。

**Comment by chitosai** [comment]
不不，这是个价值观问题，毕竟p站的图都是原创而不是转载，我还是希望想收图的人可以先去点个赞
